import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState,useEffect } from 'react'
import axios from 'axios'
import { request } from '../request/axios'
import { title } from 'process'

const inter = Inter({ subsets: ['latin'] })

interface Todo {
  id: number ;
  title:string;
}

export default function Home() {
  const [item,setItem] = useState<Array<Todo>>([]);
  useEffect(() => {
    axios.get("https://localhost:5000/api/Todo")
    .then(res => setItem(res.data))
    .catch(err => {console.log(err);
    });
  

  }, [])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>

        {item.map(({id, title}) => (
        <li key={id }>
            {title}
          </li>
          ))}
        </ul>
      </main>
    </>
  )
}
